# Generated by Django 5.0.1 on 2024-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('visitor', 'visitor'), ('moderator', 'moderator')], max_length=20, null=True),
        ),
    ]
